/**
 * ESLint configuration for the project.
 * 
 * See https://eslint.style and https://typescript-eslint.io for additional linting options.
 */
// @ts-check
import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import stylistic from '@stylistic/eslint-plugin';
import globals from 'globals';

export default tseslint.config(
	{
		ignores: [
			'**/.vscode-test',
			'**/out',
			// Generated by peggy from server/src/foxpro.pegjs -- never hand-edited.
			'server/src/parser.js',
			'server/src/parser.d.ts',
		]
	},
	js.configs.recommended,
	...tseslint.configs.recommended,
	...tseslint.configs.stylistic,
	{
		plugins: {
			'@stylistic': stylistic
		},
		rules: {
			'curly': 'off',
			'@stylistic/semi': ['warn', 'always'],
			'no-control-regex': 'warn',
			'no-empty': 'warn',
			'no-useless-escape': 'warn',
			'@typescript-eslint/no-empty-function': 'off',
			'@typescript-eslint/no-explicit-any': 'warn',
			'@typescript-eslint/no-empty-object-type': 'warn',
			'@typescript-eslint/naming-convention': [
				'warn',
				{
					'selector': 'import',
					'format': ['camelCase', 'PascalCase']
				}
			],
			'@typescript-eslint/no-unused-vars': ['warn', { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' }]
		}
	}
,
	{
		// Build scripts and the parser test harness run under plain Node, not VS Code.
		files: ['scripts/**/*.mjs'],
		languageOptions: {
			globals: globals.node,
			sourceType: 'module'
		}
	},
	{
		files: ['test-files/**/*.js'],
		languageOptions: {
			globals: globals.node,
			sourceType: 'commonjs'
		},
		rules: {
			// These harnesses load the CommonJS parser/linter build directly.
			'@typescript-eslint/no-require-imports': 'off'
		}
	}
);
