* The oldest layer: ALL-CAPS memory variables with M_/D_/T_ prefixes, PARAMETERS rather than
* LPARAMETERS, work areas held in variables, and =SEEK() called for its positioning side effect.
PARAMETERS MNM, ARR, FLD

PRIVATE D_MTPC, D_MTPC2, M_DTAITM, M_SUBFLD, T_MOSNUM, M_ITEM, M_FIRSTIME, M_LASTSUB

D_MTPC		= UDUSE("MAILTPC")
D_MTPC2		= UDUSE("MAILTPC", "MNPNSTTPDT")
M_DTAITM	= EVAL(ARR + "(" + FLD + ",6)")
M_SUBFLD	= EVAL(ARR + "(" + FLD + ",8)")
T_MOSNUM	= EVAL(ARR + "(" + FLD + "," + IIF(M_DTAITM, "3", "2") + ")")
M_ITEM		= ""
M_LASTSUB	= .F.

SELECT (D_MTPC)
DO CASE
CASE M_DTAITM
	APPEND BLANK
	REPLACE MOSNUM WITH MNM, PMNUM WITH T_MOSNUM, STAT WITH 1, TYPE WITH " ", ;
			DATA WITH .T., KEY WITH EVAL(ARR + "(" + FLD + ",2)")
	M_ITEM = EVAL(ARR + "(" + FLD + ",2)")
CASE M_SUBFLD
	APPEND BLANK
	REPLACE MOSNUM WITH MNM, PMNUM WITH T_MOSNUM, STAT WITH 1, TYPE WITH "S", ;
			DATA WITH .F., KEY WITH EVAL(ARR + "(" + FLD + ",7)")
	M_LASTSUB = .T.
OTHERWISE
	APPEND BLANK
	REPLACE MOSNUM WITH MNM, PMNUM WITH T_MOSNUM, STAT WITH 1, TYPE WITH " "
ENDCASE

M_FIRSTIME = .T.
DO ASSOC WITH T_MOSNUM, M_ITEM
USE IN MAILTPC
USE IN MNPNSTTPDT
RETURN


PROCEDURE ASSOC
	PARAMETERS T_MOSNUM, M_ITEM
	PRIVATE D_HRELATE, D_HTOPIC1, D_HTOPIC2, M_CHILDKEY

	D_HTOPIC1	= UDUSE("D HTOPIC", "MOSNUM")
	D_HTOPIC2	= UDUSE("D HTOPIC", "MOSNUM")
	D_HRELATE	= UDUSE("D HRELATE", "MOSNUM")

	SELECT (D_HRELATE)
	=SEEK(T_MOSNUM)
	SCAN REST FOR SEEK(MOSNUM, D_HTOPIC1) .AND. SEEK(PMNUM, D_HTOPIC2)
		IF &D_HRELATE->SUBDATA
			M_CHILDKEY = ALLTRIM(&D_HRELATE->CHILDKEY)
			=SEEK(M_ITEM, D_HTOPIC1)
			SELECT (D_MTPC)
			APPEND BLANK
			REPLACE MOSNUM WITH MNM, PMNUM WITH &D_HRELATE->PMNUM, STAT WITH 1, TYPE WITH "S"
			M_LASTSUB = .T.
		ELSE
			IF !SEEK(MNM + &D_HRELATE->PMNUM + "XS ", D_MTPC2)
				SELECT (D_MTPC)
				APPEND BLANK
				REPLACE MOSNUM WITH MNM, PMNUM WITH &D_HRELATE->PMNUM, STAT WITH 1
			ENDIF
		ENDIF
		M_FIRSTIME = .F.
		SELECT (D_HRELATE)
	ENDSCAN

	USE IN HRELATE
	USE IN HTOPIC1
	USE IN HTOPIC2
	RETURN
