// VFP's own functions, by name. FoxPro resolves an intrinsic before it looks for a user routine, so a routine named like one is unreachable: a `VARTYPE(m.x)` call never arrives at the `FUNCTION VARTYPE` the framework has carried since the 1990s, and nothing may resolve to it.
// Only names that really are functions belong here. A command word is not enough -- REPLACE and SCATTER are statements with no function of the same name, and a routine may be called either -- because every name listed silences a finding that would otherwise be made.

/** Every built-in function name, upper-cased, split from one string so the list reads as a list rather than as a thousand lines of quotes. */
const names = `
ABS ACLASS ACOPY ACOS ADATABASES ADBOBJECTS ADDBS ADDPROPERTY ADEL ADIR ADLLS AELEMENT AERROR AEVENTS AFIELDS AFONT AGETCLASS
AGETFILEVERSION AINS AINSTANCE ALANGUAGE ALEN ALIAS ALINES ALLTRIM AMEMBERS AMOUSEOBJ ANETRESOURCES APRINTERS APROCINFO ASC
ASCAN ASELOBJ ASESSIONS ASIN ASORT ASQLHANDLES ASTACKINFO ASUBSCRIPT AT ATAGINFO ATAN ATC ATCC ATCLINE ATLINE ATN2 AUSED AVCXCLASSES
BAR BARCOUNT BARPROMPT BETWEEN BINDEVENT BINTOC BITAND BITCLEAR BITLSHIFT BITNOT BITOR BITRSHIFT BITSET BITTEST BITXOR BOF
CANDIDATE CAPSLOCK CAST CDOW CDX CEILING CHR CHRSAW CHRTRAN CHRTRANC CLOG CMONTH CNTBAR CNTPAD COL COMARRAY COMCLASSINFO COMPOBJ
COMPROP COMRETURNERROR COS CPCONVERT CPCURRENT CPDBF CREATEBINARY CREATEOBJECT CREATEOBJECTEX CREATEOFFLINE CTOBIN CTOD CTOT
CURDIR CURSORGETPROP CURSORSETPROP CURSORTOXML CURVAL
DATE DATETIME DAY DBC DBF DBGETPROP DBSETPROP DBUSED DDEABORTTRANS DDEADVISE DDEENABLED DDEEXECUTE DDEINITIATE DDELASTERROR
DDEPOKE DDEREQUEST DDESETOPTION DDESETSERVICE DDESETTOPIC DDETERMINATE DEFAULTEXT DELETED DESCENDING DIFFERENCE DIRECTORY
DISKSPACE DISPLAYPATH DMY DODEFAULT DOW DRIVETYPE DROPOFFLINE DTOC DTOR DTOS DTOT
EDITSOURCE EMPTY EOF ERROR EVALUATE EVL EXECSCRIPT EXP
FCHSIZE FCLOSE FCOUNT FCREATE FDATE FEOF FERROR FFLUSH FGETS FIELD FILE FILETOSTR FILTER FKLABEL FKMAX FLDLIST FLOCK FLOOR
FONTMETRIC FOPEN FORCEEXT FORCEPATH FOUND FPUTS FREAD FSEEK FSIZE FTIME FULLPATH FV FWRITE
GETAUTOINCVALUE GETBAR GETCOLOR GETCP GETCURSORADAPTER GETDIR GETENV GETFILE GETFLDSTATE GETFONT GETHOST GETINTERFACE
GETNEXTMODIFIED GETOBJECT GETPAD GETPEM GETPICT GETPRINTER GETRESULTSET GETWORDCOUNT GETWORDNUM GOMONTH
HEADER HOME HOUR
ICASE IDXCOLLATE IIF IMESTATUS INDBC INDEXSEEK INKEY INLIST INPUTBOX INSMODE INT ISALPHA ISBLANK ISCOLOR ISDIGIT ISEXCLUSIVE
ISFLOCKED ISHOSTED ISLEADBYTE ISLOWER ISMEMOFETCHED ISMOUSE ISNULL ISPEN ISREADONLY ISRLOCKED ISTRANSACTABLE ISUPPER
JUSTDRIVE JUSTEXT JUSTFNAME JUSTPATH JUSTSTEM
KEY KEYMATCH
LASTKEY LEFT LEFTC LEN LENC LIKE LIKEC LINENO LOADPICTURE LOCFILE LOCK LOG LOG10 LOOKUP LOWER LTRIM LUPDATE
MAKETRANSACTABLE MAX MCOL MDOWN MDX MDY MEMLINES MEMORY MENU MESSAGE MESSAGEBOX MIN MINUTE MLINE MOD MONTH MRKBAR MRKPAD MROW
MTON MWINDOW
NDX NEWOBJECT NORMALIZE NTOM NUMLOCK NVL
OBJNUM OBJTOCLIENT OBJVAR OCCURS OEMTOANSI OLDVAL ON ORDER OS
PAD PADC PADL PADR PARAMETERS PAYMENT PCOL PCOUNT PEMSTATUS PI POPUP PRIMARY PRINTSTATUS PRMBAR PRMPAD PROGRAM PROMPT PROPER
PROW PRTINFO PUTFILE PV
QUARTER
RAISEEVENT RAND RAT RATC RATLINE RDLEVEL READKEY RECCOUNT RECNO RECSIZE REFRESH RELATION REMOVEPROPERTY REPLICATE REQUERY RGB
RGBSCHEME RIGHT RIGHTC RLOCK ROUND RTOD RTRIM
SAVEPICTURE SCHEME SCOLS SEC SECONDS SEEK SELECT SET SETFLDSTATE SETRESULTSET SIGN SIN SKPBAR SKPPAD SOUNDEX SPACE SQLCANCEL
SQLCOLUMNS SQLCOMMIT SQLCONNECT SQLDISCONNECT SQLEXEC SQLGETPROP SQLIDLEDISCONNECT SQLMORERESULTS SQLPREPARE SQLROLLBACK
SQLSETPROP SQLSTRINGCONNECT SQLTABLES SQRT SROWS STR STRCONV STREXTRACT STRTOFILE STRTRAN STUFF STUFFC SUBSTR SUBSTRC SYS SYSMETRIC
TABLEREVERT TABLEUPDATE TAG TAGCOUNT TAGNO TAN TARGET TEXTMERGE TIME TRANSFORM TRIM TTOC TTOD TXNLEVEL TXTWIDTH TYPE
UNBINDEVENTS UPDATED UPPER USED
VAL VARREAD VARTYPE VERSION
WBORDER WCHILD WCOLS WDOCKABLE WEEK WEXIST WFONT WLAST WLCOL WLROW WMAXIMUM WMINIMUM WONTOP WOUTPUT WPARENT WREAD WROWS WTITLE
WVISIBLE
XMLTOCURSOR XMLUPDATEGRAM
YEAR
`.split(/\s+/).filter(Boolean);

export const builtins: ReadonlySet<string> = new Set(names);

/** Whether VFP answers this name itself, which makes a user routine of the same name dead weight in the tree rather than something the rest of the code reaches. */
export const isBuiltin = (name: string) => builtins.has(name.toUpperCase());
